source 'http://ruby.taobao.org/'
# source 'http://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'

# gem 'rb-fsevent', '~> 0.9'
# gem 'rerun'
# gem 'shotgun'

gem 'serialport', '~> 1.1.0'
gem 'arduino_firmata'#, '~> 0.3.0'